### ISSUE TITLE
Iconos para botones y formularios

### ISSUE THREAD

**Issue by franexposito** [evenge/EVENGE#112]
Nombre: ```<i class="fa fa-user"></i>```
Apellidos: ```<i class="fa fa-user"></i>```
Email: ```<i class="fa fa-envelope-o"></i>```
Contraseña: ```<i class="fa fa-unlock-alt"></i>```
Twitter: ```<i class="fa fa-twitter"></i>```
Web: ```<i class="fa fa-link"></i>```
Telefono: ```<i class="fa fa-phone"></i>```
Editar: ```<i class="fa fa-pencil-square-o"></i>```
Borrar: ```<i class="fa fa-times"></i>```
Importar pdf: ```<i class="fa fa-file-pdf-o"></i>```
Nuevo: ```<i class="fa fa-plus"></i>```
Hora: ```<i class="fa fa-clock-o"></i>```
Fecha: ```<i class="fa fa-calendar-o"></i>```
Descripción: ```<i class="fa fa-square-o">```
Lugar: ```<i class="fa fa-globe"></i>```
Cancelar: ```<i class="fa fa-trash"></i>```

**Comment by VictorCoronas** [comment]
Añadidos nuevos botones
