### ISSUE TITLE
Dejar la aplicación funcionando aunque sea mostrando las vistas

### ISSUE THREAD

**Issue by ivanortegaalba** [evenge/EVENGE#133]
""" Se recuerda que todo lo anterior se califica de forma individual. Si una persona no ha contribuido a alguno de ellos, la puntuación en ese aspecto será cero. Si la aplicación no funciona o no están los fuentes publicados, la práctica estará suspensa."""

**Comment by ccamposfuentes** [comment]
Solucionado -> pull request #138
