### ISSUE TITLE
Meter la explicacion del provisionamiento de la documentacion en la web 

### ISSUE THREAD

**Issue by ivanortegaalba** [evenge/EVENGE#144]

**Comment by VictorCoronas** [comment]
Añadido testeo a la web:
https://github.com/evenge/evenge.github.io/blob/master/_posts/2015-02-02-testeo.md

http://evenge.github.io/test/2015/02/02/testeo/

**Comment by VictorCoronas** [comment]
Close #144 terminado de subir documentación a la web
