### ISSUE TITLE
Insertar la documentación en la web del proyecto

### ISSUE THREAD

**Issue by franexposito** [evenge/EVENGE#148]
Crear las entradas en http://evenge.github.io/

**Comment by VictorCoronas** [comment]
Añadido post en la web del proyecto sobre despliegue:
https://github.com/evenge/evenge.github.io/blob/master/_posts/2015-02-02-Despliegue.md

http://evenge.github.io/general/2015/02/02/Despliegue/

**Comment by VictorCoronas** [comment]
Añadido post en la web del proyecto sobre despliegue:
https://github.com/evenge/evenge.github.io/blob/master/_posts/2015-02-02-integraci%C3%B3n-continua.md

http://evenge.github.io/test/2015/02/02/integraci%C3%B3n-continua/

**Comment by VictorCoronas** [comment]
Añadido post en la web del proyecto sobre despliegue:
https://github.com/evenge/evenge.github.io/blob/master/_posts/2015-02-02-dockerfile.md

http://evenge.github.io/general/2015/02/02/dockerfile/
