### ISSUE TITLE
Nuevo ponente

### ISSUE THREAD

**Issue by ivanortegaalba** [evenge/EVENGE#199]

**Comment by germaaan** [comment]
Me pongo a mirarlo.

**Comment by Makova** [comment]
Y yo te acompaño.

**Comment by Makova** [comment]
Ya no.

**Comment by germaaan** [comment]
Hecho: https://github.com/evenge/EVENGE/commit/14312915147352f162ae40213c9b0bf21bb8290f

**Comment by ivanortegaalba** [comment]
Gracias @germaaan
