### ISSUE TITLE
Valorar la forma de entrar a una organización 

### ISSUE THREAD

**Issue by ivanortegaalba** [evenge/EVENGE#201]

**Comment by franexposito** [comment]
La manera mas cómoda y efectiva a mi modo de entender es que los miembros que ya estén dentro de la organización manden una invitación mediante Evenge.

**Comment by ivanortegaalba** [comment]
Si @franexposito con una invitación mediante email es lo más norma no? de hecho lo hace así GitHub

**Comment by franexposito** [comment]
Si estamos todos de acuerdo cierro este issue
