### ISSUE TITLE
Modificar Asistente

### ISSUE THREAD

**Issue by ivanortegaalba** [evenge/EVENGE#208]
Pequeño formulario extensible

**Comment by ivanortegaalba** [comment]
¿Tiene sentido?

**Comment by ccamposfuentes** [comment]
Si, puesto que ten en cuenta que al generar los diplomas si por ejemplo ha metido el apellido mal o algo asi.. o DNI por ejemplo

**Comment by franexposito** [comment]
No tiene mucho sentido tal como lo hemos planteado.
