### ISSUE TITLE
Proponer un nuevo diseño para el blog con Jekyll

### ISSUE THREAD

**Issue by ivanortegaalba** [evenge/EVENGE#215]

**Comment by ccamposfuentes** [comment]
nuevo tema provisional a espera de aceptación http://evenge.github.io

**Comment by franexposito** [comment]
Me molaría algo más que tenga que ver con evenge. Eso pinta más para un portfolio creo yo.

**Comment by VictorCoronas** [comment]
No esta mal el tema la verdad. Me gusta :)
