### ISSUE TITLE
Planteamiento, de relaciones en NDB y formas de "relacionar" evento con ponente

### ISSUE THREAD

**Issue by ivanortegaalba** [evenge/EVENGE#240]
Nuestro diseño, en el diagrama de clases, pensamos que necesitaríamos una tabla externa para representar al relación N-N que existe entre eventos y ponentes.

Haciendo esto, estamos forzando un diseño relacional en un modelo no relacional como es el Datastore.

Es una posibilidad, pero, la integridad hemos de salvaguardarla mediante los métodos de inserción, modificación y borrado de las respectivas clases.

La otra opción es implementar verdaderamente un modelo NoSQL, donde se independizan totalmente el Evento del Ponente, y se "rompe la relación".
Cuando digo, "se rompe" me refiero a nivel de diseño, no obviamente a nivel semántico.

La forma de "romperla" y hacer un verdadero NoSQL es independizando las colecciones de Eventos frente a las de Ponentes: 
- **Teniendo una copia de los eventos en los que participa un ponente, como campo de Evento** ya sea por medio de una estructura, un vector de objetos, o usando un diccionario. 
- Y al igual que en ponente, **tendríamos uno o varios campos que contengan la información de los eventos en los que participa**.

Según me ha explicado Pablo Hinojosa (Psicobyte) el proceder de los modelos NoSQL es este, ya que lo que busca es el poder distribuir los datos en distintos sitios, y no tener que hacer réplicas de ellos, como pasaría con el diseño relacional.

**TENEMOS LAS DOS POSIBILIDADES**:
- Forzar el SQL
- Implementar un NoSQL independizando Entities

**Comment by franexposito** [comment]
Usuario tendría:
   - Eventos
   - Ponentes

Eventos tendría:
   - Ponentes
   - Asistentes

Organización tendría:
   - Eventos
   - Usuarios
   - Ponentes

**Comment by franexposito** [comment]
Deberiamos entonces tener en el Usuario:
 - organización a la que pertenece el usuario

En Evento:
- listado de ponentes
- listado de asistentes

En organizacion
- listado de usuarios
- listado de eventos
- listado de ponentes 

En ponente
- listado de eventos

La duda que tengo es: en Usuario,¿ el listado de organizacion deberia tambien tener el listado de eventos de esa organizacion?

Es decir, ¿la misma información aparecerá al completo en todas las entidades que estén relacionadas entre si?

**Comment by franexposito** [comment]
Por lo tanto siguiendo mi anterior comentario tendríamos un problema ya que GAE no permite almacenar en datos del tipo StructuredProperty dentro de otros que StructuredProperty.
Existe un LocalStructuredProperty pero no se pueden realizar filtros a la hora de hacer las consultas sobre el por lo cual perderíamos la potencia de búsqueda de las bases de datos NoSQL.
Quizás @JJ pueda echarnos una mano en este asunto.

**Comment by JJ** [comment]
Me falta un poquito de contexto. Yo lo que diría es que tratárais de
replanteároslo. ¿Por qué necesitáis almacenar eso? ¿Por qué tratáis de
hacerlo así? ¿Podéis convertir los tipos en otro tipo? Structured property
serán cosas de tpo clave-valor, ¿no?

El 8 de junio de 2015, 20:15, Fran Expósito <notifications@github.com>
escribió:

> Por lo tanto siguiendo mi anterior comentario tendríamos un problema ya
> que GAE no permite almacenar en datos del tipo StructuredProperty dentro de
> otros que StructuredProperty.
> Existe un LocalStructuredProperty pero no se pueden realizar filtros a la
> hora de hacer las consultas sobre el por lo cual perderíamos la potencia de
> búsqueda de las bases de datos NoSQL.
> Quizás @JJ <https://github.com/JJ> pueda echarnos una mano en este asunto.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evenge/EVENGE/issues/240#issuecomment-110095895>.
>



-- 
JJ

**Comment by franexposito** [comment]
StructuredProperty es un tipo de dato que almacena una estructura o una entidad como propiedad de otra. En nuestro caso tenemos varias relaciones de las base de datos tradicionales de entidad/relación que tenemos que romper. Organizacion-Usuario, Evento-Asistente, Evento-Ponente, Usuario-Ponente. La manera de proceder de las bases de datos NoSQL, según nos explicó Psicobyte, es la de redundar la información en cada Entidad. Es decir, la información de todos los usuarios pertenecientes a un organización se almacenan en la organización y la información de la organización se almacena en cada uno de los usuarios que pertenecen a ella. No se si es esa la manera de hacerlo o entendimos mal @JJ

**Comment by JJ** [comment]
El 9 de junio de 2015, 8:43, Fran Expósito <notifications@github.com>
escribió:

> StructuredProperty es un tipo de dato que almacena una estructura o una
> entidad como propiedad de otra. En nuestro caso tenemos varias relaciones
> de las base de datos tradicionales de entidad/relación que tenemos que
> romper. Organizacion-Usuario, Evento-Asistente, Evento-Ponente,
> Usuario-Ponente. La manera de proceder de las bases de datos NoSQL, según
> nos explicó Psicobyte, es la de redundar la información en cada Entidad. Es
> decir, la información de todos los usuarios pertenecientes a un
> organización se almacenan en la organización y la información de la
> organización se almacena en cada uno de los usuarios que pertenecen a ella.
> No se si es esa la manera de hacerlo o entendimos mal @JJ
> <https://github.com/JJ>
>
>
En algunos casos se hace así, sí. El problema es qué estructura de datos
usar. Si no podéis anidar las estructuras de datos tendréis que convertirla
en otra diferente. También podéis usar "integridad referencial" a base de
IDs únicos; eso también os lo permiten las NoSQL (aunque igual hay que
hacer alguna cosa a mano)

De todas formas enlazad el código a ver si me hago una idea de qué queréis
hacer...

**Comment by franexposito** [comment]
@JJ te pongo un ejemplo detallado:

Tenemos la entidad [evento](https://github.com/evenge/EVENGE/blob/fran/_oo/classes/evento.py) y la entidad [ponente](https://github.com/evenge/EVENGE/blob/fran/_oo/classes/ponente.py).
La relación que existe entre ellos es que un Evento tiene varios ponentes que participan en ese evento y a su vez un ponente tiene los eventos en los que ha participado.
De la manera en la que entendimos como funciona NoSQL, tendriamos que almacenar a los ponentes en el Evento, lo cual se hace en esta línea:
```
ponentes = ndb.LocalStructuredProperty(Ponente, repeated=True)
```

Y después los eventos en el ponente, que se hace con esta línea:

```
ponentes = ndb.LocalStructuredProperty(Ponente, repeated=True)
```

Ahora tenemos dos problemas, uno es que StructuredProperty no permite almacenar dentro de este tipo de dato, otros datos que ya tengan StructuredProperty. Eso se soluciona utilizando LocalStructuredProperty que es similar salvo que no permite realizar busquedas.

Por lo que yo tengo entendido, en NoSQL se utiliza para almacenar grandes cantidades de información y realizar operaciones con esa información, pero no es especialmente buena a la hora de relacionar esos documentos. Para eso habría que utilizar SQL.
La solución que nos planteamos es la de redundar la información. Cada entidad funciona de manera "independiente" en el sentido de que cada uno guarda su propia información.

No se si me he explicado correctamente, podríamos concretar alguna cita en la OSL si no queda claro.

**Comment by JJ** [comment]
Sí, más o menos. A ver, a estas alturas es complicado que os paséis al SQL
de toda la vida, pero es algo que igual podríais haber considerado al
principio. Cuando hay relaciones, SQL lo maneja bastante bien. Pero vamos a
lo mismo de antes. La forma de relacionar una tabla con otra no es incluir
toda la información (aunque en BDs rápidas como Redis se hace así), sino
usar la misma técnica que en SQL: IDs únicos. En vez de incluir el objeto
entero, incluís el ID de un objeto (o documento, según la BD SQL). Mediante
una petición "a mano", podéis recuperar el objeto y todos los objetos
asociados. Para eso se usan en Python y otros lenguajes ORMs (object
relational manager) que describen a nivel de lenguaje todas las relaciones
de la BD y te lo hacen automáticamente. Tenéis todos estos en Python
http://en.wikipedia.org/wiki/List_of_object-relational_mapping_software#Python
incluso uno en el propio Django. Echadles un vistazo...

**Comment by franexposito** [comment]
@JJ es lo que utilizábamos desde un primer momento, los id unicos.

Gracias por la ayuda.

**Comment by JJ** [comment]
Entonces, ¿no podéis usar los id únicos en de una StructuredProperty en vez de la StructuredProperty en sí?

**Comment by franexposito** [comment]
@JJ simplemente PsicoByte nos propuso otro planteamiento y teníamos muchas dudas de cual era mejor.
