### ISSUE TITLE
¿Requerimientos para la pimera beta?

### ISSUE THREAD

**Issue by ivanortegaalba** [evenge/EVENGE#242]
Hemos estado hablado @ccamposfuentes y yo de hacer una primera beta ya, y ver cuando podemos darsela a la OSL para que vayan evaluándola y sacando errores.

La presentación y entrega para el concurso es el 29 de Junio. Os propongo @ccamposfuentes , @franexposito y @VictorCoronas que añadáis al milestone creado los issues que veáis oportunos añadir.

**Comment by VictorCoronas** [comment]
Me parece perfecto :), sin ningun problema, vamos poniendo issues.

**Comment by franexposito** [comment]
¿Cuando hay que entregar la primera beta?

**Comment by ivanortegaalba** [comment]
@franexposito @ccamposfuentes @VictorCoronas el día 15 es la presentación del proyecto. Ya están evaluando los proyectos, por lo que necesitaríamos ir a la @OSLUGR cuanto antes, para hablar con ellos y darle la primera beta.

**Comment by franexposito** [comment]
Vale, ahora mirate este issue #240

**Comment by ivanortegaalba** [comment]
¿Que pasa?
