### ISSUE TITLE
Eliminación de la información de issues/commit por desarrollador

### ISSUE THREAD

**Issue by franexposito** [evenge/EVENGE#249]
Puesto que ya hemos terminado IV no le veo sentido el tener en el archivo README los enlaces con los issues/commits de cada uno. Propongo eliminarlos.

**Comment by ccamposfuentes** [comment]
La verdad es que si ...

**Comment by VictorCoronas** [comment]
pue si quereis a eliminarlo que no hace falta, adelante...

2015-06-09 20:56 GMT+02:00 Carlos Campos <notifications@github.com>:
